global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"
  - job_name: api
    static_configs:
      - targets:
          - "api:4000"
