name: otomad-database-api-prod
version: "3.9"

services:
  api:
    build:
      context: ./.
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      neo4j:
        condition: service_healthy
    environment:
      PORT: 4000
      HOST: "0.0.0.0"

      PRISMA_DATABASE_URL: "postgres://user:pass@postgres:5432/test"

      NEO4J_URL: "bolt://neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "password"
    ports:
      - target: 4000
        published: 4000

  postgres:
    image: postgres:15
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  migration:
    build:
      context: ./.
      dockerfile: Dockerfile.migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PRISMA_DATABASE_URL: "postgres://user:pass@postgres:5432/test"

  neo4j:
    image: neo4j:5.4
    environment:
      NEO4J_AUTH: neo4j/password
    healthcheck:
      test: neo4j status || exit 1 # TODO:
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs

  prometheus:
    image: prom/prometheus:v2.4.0
    ports:
      - target: 9090
        published: 9090
    volumes:
      - type: bind
        source: ./prometheus/prod/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: volume
        source: prometheus_data
        target: /prometheus

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - target: 3000
        published: 9000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - type: bind
        source: ./grafana/prod/dashboards
        target: /etc/grafana/dashboards
      - type: bind
        source: ./grafana/prod/provisioning
        target: /etc/grafana/provisioning
      - type: volume
        source: grafana_data
        target: /etc/grafana/dashboards

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  grafana_data:
  prometheus_data:
