version: "3.9"

services:
  postgres:
    image: postgres:15
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - target: 8080
        published: 8081

volumes:
  postgres_data:
