name: otomad-database-api
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:4d15cb8c1b38dc2c0351cf7f3b3f1c663e493a76fa52be6179c8b12660021772
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer@sha256:16d5b637e94d2e3206c531d0dc22207467dc1160c071d4d75c64b7ccee08f360
    ports:
      - target: 8080
        published: 8081

  neo4j:
    image: neo4j:5.15@sha256:0a3c9c4eb4cb09bd30ddae5ded33edba2bdaa1d1f263709e3b834fc9040c9d6d
    ports:
      # http
      - target: 7474
        published: 7474
      # bolt
      - target: 7687
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password

  meilisearch:
    image: getmeili/meilisearch:v1.0@sha256:dd8162da4cebbdec1ab6176754cff941b04427e7f8df532896a920ec3d292d8a
    ports:
      - target: 7700
        published: 7700
    volumes:
      - type: volume
        source: meilisearch_data
        target: /meili_data

  redis:
    image: redis:7.2@sha256:b5ddcd52d425a8e354696c022f392fe45fca928f68d6289e6bb4a709c3a74668
    ports:
      - target: 6379
        published: 6379

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  meilisearch_data:
