name: otomad-database-api-test
version: "3.9"

services:
  postgres:
    image: postgres:15
    ports:
      - target: 5432
        published: 5433
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test

  # postgres-migration:
  #   build:
  #     context: ./.
  #     dockerfile: Dockerfile.migration
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     PRISMA_DATABASE_URL: "postgres://user:pass@postgres:5432/test"

  neo4j:
    image: neo4j:5.2
    ports:
      - target: 7687
        published: 7688
    environment:
      NEO4J_AUTH: neo4j/password
