name: otomad-database-api
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:5d87228bf5536ebcb46e5834d9b49b5640d51f45ad286860fef190e3a212a81c
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer@sha256:0ce7583815dabdd9f560ee0afed630ecb33df6756f4b66c85c197011559a0248
    ports:
      - target: 8080
        published: 8081

  neo4j:
    image: neo4j:5.13@sha256:03a759ba2741d367f0487ca16508237a942d59576e9f7984de3394dd04b03caf
    ports:
      # http
      - target: 7474
        published: 7474
      # bolt
      - target: 7687
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password

  meilisearch:
    image: getmeili/meilisearch:v1.0@sha256:dd8162da4cebbdec1ab6176754cff941b04427e7f8df532896a920ec3d292d8a
    ports:
      - target: 7700
        published: 7700
    volumes:
      - type: volume
        source: meilisearch_data
        target: /meili_data

  redis:
    image: redis:7.0@sha256:76a65ef2077aa851df76a86da26d2f1e81fe5a19c7ca749c9d4ccc200e1eac96
    ports:
      - target: 6379
        published: 6379

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  meilisearch_data:
