name: otomad-database-api
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:79aff09d6a4051942be9f2b0288d15a1b23626f2e69200c2fceee4027c13374b
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer@sha256:0ce7583815dabdd9f560ee0afed630ecb33df6756f4b66c85c197011559a0248
    ports:
      - target: 8080
        published: 8081

  neo4j:
    image: neo4j:5.14@sha256:3ccfe0fcc51436087128ff8e1905d6758f80f300743a06f624a1718ab720de96
    ports:
      # http
      - target: 7474
        published: 7474
      # bolt
      - target: 7687
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password

  meilisearch:
    image: getmeili/meilisearch:v1.0@sha256:dd8162da4cebbdec1ab6176754cff941b04427e7f8df532896a920ec3d292d8a
    ports:
      - target: 7700
        published: 7700
    volumes:
      - type: volume
        source: meilisearch_data
        target: /meili_data

  redis:
    image: redis:7.2@sha256:2976bc0437deff693af2dcf081a1d1758de8b413e6de861151a5a136c25eb9e4
    ports:
      - target: 6379
        published: 6379

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  meilisearch_data:
