version: "3.9"

services:
  mongo:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: otomadb
    ports:
      - target: 27017
        published: 27017
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
  neo4j:
    image: neo4j:5.2
    ports:
      # http
      - target: 7474
        published: 7474
      # bolt
      - target: 7687
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password

volumes:
  mongo_data:
  neo4j_data:
  neo4j_logs:
