name: otomad-database-api
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:cc6dcc9ec987ce2887ac746114a72b288e490ba14f4658731c2822600aab8d00
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer@sha256:0ce7583815dabdd9f560ee0afed630ecb33df6756f4b66c85c197011559a0248
    ports:
      - target: 8080
        published: 8081

  neo4j:
    image: neo4j:5.14@sha256:677d3ad677cbf3993db10b60cf990b0df394687210df3f1ce124459ae8542e64
    ports:
      # http
      - target: 7474
        published: 7474
      # bolt
      - target: 7687
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password

  meilisearch:
    image: getmeili/meilisearch:v1.0@sha256:dd8162da4cebbdec1ab6176754cff941b04427e7f8df532896a920ec3d292d8a
    ports:
      - target: 7700
        published: 7700
    volumes:
      - type: volume
        source: meilisearch_data
        target: /meili_data

  redis:
    image: redis:7.2@sha256:396b0f027ba2f33bf385771a621b58c1fd834fd2c522c35c98fd24fc17863c2f
    ports:
      - target: 6379
        published: 6379

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  meilisearch_data:
