name: otomad-database-api-test
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:3faff326de0fa3713424d44f3b85993459ac1917e0a4bfd35bab9e0a58e41900
    ports:
      - target: 5432
        published: 5433
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test

  # postgres-migration:
  #   build:
  #     context: ./.
  #     dockerfile: Dockerfile.migration
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     PRISMA_DATABASE_URL: "postgres://user:pass@postgres:5432/test"

  neo4j:
    image: neo4j:5.13@sha256:5ba8a00a38444cc07623f3de1dd72d0f8cc3dcd64a198c8d87af5a64f65c8457
    ports:
      - target: 7687
        published: 7688
    environment:
      NEO4J_AUTH: neo4j/password

  redis:
    image: redis:7.0@sha256:d634d2c07d1f70672aa2e8c2443643b23b5755ecfc068685b0dcf0b76a9db72b
    ports:
      - target: 6379
        published: 6380
