name: otomad-database-api-test
version: "3.9"

services:
  postgres:
    image: postgres:15@sha256:d1168ad5397bf9c94cc417c530469805a8767ed585481d93f174461ac8557e3a
    ports:
      - target: 5432
        published: 5433
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test

  # postgres-migration:
  #   build:
  #     context: ./.
  #     dockerfile: Dockerfile.migration
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     PRISMA_DATABASE_URL: "postgres://user:pass@postgres:5432/test"

  neo4j:
    image: neo4j:5.13@sha256:a41a24815b24614ce7a5b90e88bf3eaf805671d9bbecab0c63b212ba7512542f
    ports:
      - target: 7687
        published: 7688
    environment:
      NEO4J_AUTH: neo4j/password

  redis:
    image: redis:7.0@sha256:bc6c4e52769a07420ebde23364c2dbabe3ba1e8652d163758cad5de3a027bd4f
    ports:
      - target: 6379
        published: 6380
