name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - run: pnpm run lint:schema
      - run: pnpm run lint:eslint
      - run: pnpm run lint:prettier

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run typecheck

  test:
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL: postgres://postgres:pass@localhost/postgres
      TEST_NEO4J_URL: bolt://neo4j:password@localhost:7687
      TEST_NEO4J_USERNAME: neo4j
      TEST_NEO4J_PASSWORD: password
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pass
      neo4j:
        image: neo4j:5.2
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/password
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - run: pnpm run codegen
      - run: pnpm run test
