name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: true
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run lint:eslint
      - run: npm run lint:prettier
      - run: npm run codegen
      - run: npm run lint:graphql-schema-linter

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DATABASE: test
      NEO4J_URL: bolt://localhost:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
    services:
      postgres:
        image: postgres:15@sha256:967fae8e6eeaa6be820fab3f35f4b90931a2f61c08dbd15e2d75ddf6bccf5a2a
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}
      neo4j:
        image: neo4j:5.14@sha256:677d3ad677cbf3993db10b60cf990b0df394687210df3f1ce124459ae8542e64
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: ${{ env.NEO4J_USERNAME }}/${{ env.NEO4J_PASSWORD }}
      redis:
        image: redis:7.2@sha256:a551fdb6b6a6e323c76131ece01205f9d722d1f1589c4d85aa27eab19870f16e
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: true
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run prebuild
      - run: npm run test
        env:
          PRISMA_DATABASE_URL: postgres://${{ env.POSTGRES_USERNAME }}:${{ env.POSTGRES_PASSWORD }}@localhost:5432/${{ env.POSTGRES_DATABASE }}
          NEO4J_URL: ${{ env.NEO4J_URL }}
          NEO4J_USERNAME: ${{ env.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ env.NEO4J_PASSWORD }}
          REDIS_URL: "redis://localhost:6379"
