name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npm run codegen
      - run: npm run prisma:client
      - run: npm run lint:schema
      - run: npm run lint:eslint
      - run: npm run lint:prettier

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npm run codegen
      - run: npm run prisma:client
      - run: npm run typecheck

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TEST_PRISMA_DATABASE_URL: postgres://user:pass@localhost:5432/test
      TEST_NEO4J_URL: bolt://localhost:7687
      TEST_NEO4J_USERNAME: neo4j
      TEST_NEO4J_PASSWORD: password
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test
      neo4j:
        image: neo4j:5.4
        ports:
          - 7687:7687
        env:
          NEO4J_AUTH: neo4j/password
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - run: npm ci
      - run: npm run codegen
      - run: npm run prisma:client
      - run: npm run e2e-test:migration
      - run: npm run e2e-test
