name: Docker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@v6.4.0
        id: image_tag
        with:
          result-encoding: string
          script: |
            if (context.eventName === "push") return process.env.GITHUB_REF_NAME
            else return `build-${process.env.GITHUB_RUN_NUMBER}`

      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ghcr.io/${{ github.repository_owner }}/api:${{ steps.image_tag.outputs.result }}

  migration:
    name: Migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.migration

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@v6.4.0
        id: image_tag
        with:
          result-encoding: string
          script: |
            if (context.eventName === "push") return process.env.GITHUB_REF_NAME
            else return `build-${process.env.GITHUB_RUN_NUMBER}`

      - uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile.migration
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ghcr.io/${{ github.repository_owner }}/api-postgres-migration:${{ steps.image_tag.outputs.result }}
