name: Docker(api)

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "package.json"
      - "package-lock.json"
      - ".npmrc"
      - "src/**"
      - "prisma/schema.prisma"
      - "codegen-plugins/**"
  pull_request:
  merge_group:

jobs:
  build:
    name: Build api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2
      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image_tag
        name: Determine image tag
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          result-encoding: string
          script: |
            if (context.eventName === "push" && context.ref.startsWith("refs/tags/v"))
              return context.ref.substring(11)
            else if (context.eventName === "push" && context.ref === "refs/heads/main")
              return "latest"
            else
              return context.sha
        # pull_requestではcontext.shaすなわちGITHUB_SHAの値には若干違う値が入るが支障はないので無視する．
        # ref: https://sue445.hatenablog.com/entry/2021/01/07/004835

      - uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/api:${{ steps.image_tag.outputs.result }}
