name: Docker(api)

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".dockerignore"
      - "package.json"
      - "package-lock.json"
      - ".npmrc"
      - "src/**"
      - "prisma/schema.prisma"
      - "codegen-plugins/**"
  pull_request:
  merge_group:

jobs:
  build:
    name: Build api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: Dockerfile

      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: image_tag
        name: Determine image tag
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          result-encoding: string
          script: |
            if (context.eventName === "push" && context.ref.startsWith("refs/tags/v"))
              return context.ref.substring(11)
            else if (context.eventName === "push" && context.ref === "refs/heads/main")
              return "latest"
            else
              return context.sha
        # pull_requestではcontext.shaすなわちGITHUB_SHAの値には若干違う値が入るが支障はないので無視する．
        # ref: https://sue445.hatenablog.com/entry/2021/01/07/004835

      - uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/api:${{ steps.image_tag.outputs.result }}
